ATTRIBUTE_RELATIONS = {
    "Time",
    "Literal",
    "Numeric",
    "Tag",
}

RELATION_RELATIONS = {
    "Work",
    "Character",
    "Person",
    "Organization",
    "Group",
    "Location",
}

DEFAULT_GRAPH = {
    "nodes": [
        {
            "id": 1,
            "name": "Alice",
            "group": "Engineering",
            "properties": {
                "age": 25,
                "role": "Frontend Developer",
                "email": "alice@company.com",
                "location": "New York",
                "start_date": "2022-03-15",
                "skills": ["React", "JavaScript", "CSS"],
            },
        },
        {
            "id": 2,
            "name": "Bob",
            "group": "Engineering",
            "properties": {
                "age": 30,
                "role": "Backend Developer",
                "email": "bob@company.com",
                "location": "San Francisco",
                "start_date": "2020-06-01",
                "skills": ["Python", "Django", "PostgreSQL"],
            },
        },
        {
            "id": 3,
            "name": "Carol",
            "group": "Design",
            "properties": {
                "age": 28,
                "role": "UI/UX Designer",
                "email": "carol@company.com",
                "location": "London",
                "start_date": "2021-01-20",
                "skills": ["Figma", "Sketch", "Adobe XD"],
            },
        },
        {
            "id": 4,
            "name": "Dave",
            "group": "HR",
            "properties": {
                "age": 35,
                "role": "HR Manager",
                "email": "dave@company.com",
                "location": "Berlin",
                "start_date": "2018-09-10",
                "skills": ["Recruiting", "Payroll", "Employee Relations"],
            },
        },
        {
            "id": 5,
            "name": "Eve",
            "group": "Engineering",
            "properties": {
                "age": 22,
                "role": "Intern",
                "email": "eve@company.com",
                "location": "New York",
                "start_date": "2023-07-01",
                "skills": ["Python", "HTML", "CSS"],
            },
        },
        {
            "id": 6,
            "name": "Frank",
            "group": "Design",
            "properties": {
                "age": 40,
                "role": "Lead Designer",
                "email": "frank@company.com",
                "location": "London",
                "start_date": "2015-04-05",
                "skills": ["Adobe Suite", "Branding", "UI/UX"],
            },
        },
        {
            "id": 7,
            "name": "Grace",
            "group": "Engineering",
            "properties": {
                "age": 26,
                "role": "DevOps Engineer",
                "email": "grace@company.com",
                "location": "San Francisco",
                "start_date": "2021-11-12",
                "skills": ["AWS", "Docker", "Kubernetes"],
            },
        },
        {
            "id": 8,
            "name": "Heidi",
            "group": "Marketing",
            "properties": {
                "age": 29,
                "role": "Content Strategist",
                "email": "heidi@company.com",
                "location": "Berlin",
                "start_date": "2019-08-20",
                "skills": ["SEO", "Content Writing", "Social Media"],
            },
        },
        {
            "id": 9,
            "name": "Ivan",
            "group": "Marketing",
            "properties": {
                "age": 31,
                "role": "SEO Specialist",
                "email": "ivan@company.com",
                "location": "Berlin",
                "start_date": "2020-02-15",
                "skills": ["SEO", "Analytics", "Google Ads"],
            },
        },
        {
            "id": 10,
            "name": "Judy",
            "group": "Engineering",
            "properties": {
                "age": 24,
                "role": "QA Engineer",
                "email": "judy@company.com",
                "location": "New York",
                "start_date": "2022-09-01",
                "skills": ["Testing", "Selenium", "Jira"],
            },
        },
    ],
    "links": [
        {"source": 1, "target": 2, "type": "works_with"},
        {"source": 1, "target": 3, "type": "collaborates"},
        {"source": 2, "target": 4, "type": "reports_to"},
        {"source": 3, "target": 5, "type": "mentors"},
        {"source": 2, "target": 6, "type": "collaborates"},
        {"source": 6, "target": 7, "type": "collaborates"},
        {"source": 5, "target": 8, "type": "reports_to"},
        {"source": 7, "target": 9, "type": "works_with"},
        {"source": 8, "target": 10, "type": "mentors"},
        {"source": 9, "target": 10, "type": "works_with"},
        {"source": 3, "target": 7, "type": "collaborates"},
        {"source": 4, "target": 8, "type": "manages"},
    ],
}
